name = "salon-vectorize-setup"
main = "src/index.js"
compatibility_date = "2025-04-01"

# Configure custom domain
routes = [
  { pattern = "vectorized-salonchat.zodworks.dev", custom_domain = true }
]

# Disable workers.dev domain
workers_dev = false

# Bind the salon database
[[d1_databases]]
binding = "SALON_DB"
database_name = "salon-db"
database_id = "f2445643-edc0-4dc9-85d2-d094290dcfa6"

# Bind AI for embeddings
[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

# Create binding for the vector index
[[vectorize]]
binding = "SALON_VECTORIZE"
index_name = "salon-vectorize"
