name = "salon-chat-frontend"
main = "workers-site/index.js"
compatibility_date = "2024-04-02"

# Configure custom domain
routes = [
  { pattern = "salonchat.zodworks.dev", custom_domain = true }
]

# Set Zero Trust features
workers_dev = false

# Static assets serving
[site]
bucket = "./dist"

# Bind to Cloudflare Pages deployment for ASSETS
# [[services]]
# binding = "ASSETS"
# service = "salonchat-frontend"
# environment = "production"

# logging
[observability]
enabled = true
head_sampling_rate = 1

# Environment variables
[vars]
API_WORKER_URL = "https://salonchat-api.zodworks.dev"
PAGES_URL = "https://salonchat-frontend.pages.dev"

# Service tokens - replace with actual values
SERVICE_TOKEN_CLIENT_ID = "69a4458c2f6ba25ed8c6bb05bfc26bd1.access"
SERVICE_TOKEN_CLIENT_SECRET = "62edf4cc29ffe98457a75371f6575e394a725a680e6a8a3bf4f766620623d326"

